### ISSUE TITLE
Install is borked, wont work

### ISSUE THREAD

**Issue by 2blackbar** [imb101/ComfyUI-FaceSwap#1]
ote: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FaceSwap\install.py", line 27, in ensure_pip_packages
    import cython
ModuleNotFoundError: No module named 'cython'

`Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FaceSwap\install.py", line 27, in ensure_pip_packages
    import cython
ModuleNotFoundError: No module named 'cython'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FaceSwap\__init__.py", line 2, in <module>
    install()
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FaceSwap\install.py", line 34, in install
    ensure_pip_packages()
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FaceSwap\install.py", line 31, in ensure_pip_packages
    subprocess.check_call(pip_install + ['-r', requirements_path])
  File "subprocess.py", line 413, in check_call
subprocess.CalledProcessError: Command '['G:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-s', '-m', 'pip', 'install', '-r', 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-FaceSwap\\requirements.txt']' returned non-zero exit status 1.

Cannot import G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FaceSwap module for custom nodes: Command '['G:\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-s', '-m', 'pip', 'install', '-r', 'G:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-FaceSwap\\requirements.txt']' returned non-zero exit status 1.
### ComfyUI Revision: 1264 [0ce8a540]
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_pixelization\__init__.py", line 9, in <module>
    from .modules import devices, shared
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_pixelization\modules\shared.py", line 8, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'`

**Comment by hashtagamazing** [comment]
got the same error, any solution?
