### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by nyukers** [imb101/ComfyUI-FaceSwap#2]
Traceback (most recent call last):
  File "C:\SDComfyUI\ComfyUI\nodes.py", line 1693, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\SDComfyUI\ComfyUI\custom_nodes\ComfyUI-FaceSwap\__init__.py", line 4, in <module>
    from .FaceSwapNode import FaceSwapNode
  File "C:\SDComfyUI\ComfyUI\custom_nodes\ComfyUI-FaceSwap\FaceSwapNode.py", line 1, in <module>
    import insightface
  File "C:\SDComfyUI\python_embeded\lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "C:\SDComfyUI\python_embeded\lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "C:\SDComfyUI\python_embeded\lib\site-packages\insightface\app\mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "C:\SDComfyUI\python_embeded\lib\site-packages\insightface\thirdparty\face3d\__init__.py", line 3, in <module>
    from . import mesh
  File "C:\SDComfyUI\python_embeded\lib\site-packages\insightface\thirdparty\face3d\mesh\__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
ImportError: DLL load failed while importing mesh_core_cython: The specified module could not be found.

**Windows 10 Pro, ComfyUI Portable.**

**Comment by nyukers** [comment]
Solved, thank you all.

**Comment by nyukers** [comment]
Done
